-- ========================================================
-- DIGIWISE DATABASE INITIALIZATION & ACCESS FIX SCRIPT
-- ========================================================

-- 1. Create Admins Table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Users (Publishers/Advertisers) Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    status TEXT DEFAULT 'Active',
    type TEXT DEFAULT 'Publisher',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Campaigns Table
CREATE TABLE IF NOT EXISTS campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    offer_id TEXT,
    country TEXT,
    link TEXT,
    type TEXT DEFAULT 'Click',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Assignments Table
CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES admins(id) ON DELETE CASCADE,
    campaign_id BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
    count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT uk_user_camp UNIQUE(user_id, campaign_id),
    CONSTRAINT uk_admin_camp UNIQUE(admin_id, campaign_id),
    CONSTRAINT ck_assignment_target CHECK (
        (user_id IS NOT NULL AND admin_id IS NULL) OR
        (user_id IS NULL AND admin_id NOT NULL)
    )
);

-- 5. DISABLE ROW LEVEL SECURITY (RLS) FOR API ACCESS
ALTER TABLE admins DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE assignments DISABLE ROW LEVEL SECURITY;

-- 6. Insert Default Admin Account
DELETE FROM admins WHERE email = 'admin@admin.com';
INSERT INTO admins (name, email, password, status)
VALUES ('DigiWise Admin', 'admin@admin.com', 'admin123', 'Active');
